version: "3.8"

services:
  cve_api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/database  # SQLite-Datenbank persistent speichern
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: cve_db
      POSTGRES_USER: cve_user
      POSTGRES_PASSWORD: cve_password
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cve_user -d cve_db"]
      interval: 5s
      retries: 5

volumes:
  database:
#version: "3.8"

#services:
#  cve_api:
#    build: .
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./app:/app
#    environment:
#      - FLASK_APP=main.py
#      - FLASK_RUN_HOST=0.0.0.0
